# Generated by Django 3.0.7 on 2020-08-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passsenger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passsenger',
            new_name='Passenger',
        ),
    ]
